version: '3.8'

services:
  # postgres:
  #   container_name: postgres
  #   restart: always
  #   image: postgres:latest
  #   volumes:
  #     - ./database:/var/lib/postgresql/data
  #   ports:
  #     - "5432:5432"
  #   environment:
  #     POSTGRES_USER: yourusername
  #     POSTGRES_PASSWORD: yourpassword
  #     POSTGRES_DB: yourdatabase
  backend:
    container_name: backend
    image: my-medusa-backend
#    image: docker.io/beejay/my-h-bees:latest
    restart: always
    environment:    
      - DATABASE_URL=postgres://pgbajonczak:n4@NMvumg-dTNop@postgrbajonczak.postgres.database.azure.com/postgres?sslmode=require
      - MEDUSA_ADMIN_ONBOARDING_TYPE=nextjs
      - ALLOWED_HOSTS=http://localhost:5173,http://localhost:8080,https://docs.medusajs.com,http://shop.myhealthybees.com
      - STORE_CORS=http://localhost:8000,https://docs.medusajs.com,http://shop.myhealthybees.com
      - ADMIN_CORS=http://localhost:5173,http://localhost:8080,https://docs.medusajs.com,http://shop.myhealthybees.com
      - AUTH_CORS=http://localhost:5173,http://localhost:8080,http://shop.myhealthybees.com,http://localhost:8000,https://docs.medusajs.com
      - REDIS_URL=redis://redis_server:6379
      - JWT_SECRET=supersecret
      - COOKIE_SECRET=supersecret
      - MEDUSA_BACKEND_URL= http://shop.myhealthybees.com
      - MEDUSA_ADMIN_ONBOARDING_NEXTJS_DIRECTORY=my-h-bees-storefront
      - DB_NAME=medusa-my-h-bees
    ports:
      - "8080:8080"
    depends_on:
      - redis
  redis:
    container_name: redis_server
    image: redis:latest
    restart: always
    # network_mode: bridge
    ports:
      - "6379:6379"
  store:
    container_name: frontend
    image: my-medusa-frontend:latest
    restart: always
    network_mode: bridge
    environment:
      - NEXT_PUBLIC_MEDUSA_BACKEND_URL=http://shop.myhealthybees.com:8080
      - NEXT_PUBLIC_BASE_URL=http://127.0.0.1:8000     
#      - MEDUSA_BACKEND_URL=http://shop.myhealthybees.com:8080
#      - BACKEND_URL=http://shop.myhealthybees.com:8080




      # Your Medusa backend, should be updated to where you are hosting your server. Remember to update CORS settings for your server. See – https://docs.medusajs.com/usage/configurations#admin_cors-and-store_cors
      - MEDUSA_BACKEND_URL= http://shop.myhealthybees.com:8080

      # Your publishable key that can be attached to sales channels. See - https://docs.medusajs.com/development/publishable-api-keys
      - NEXT_PUBLIC_MEDUSA_PUBLISHABLE_KEY= pk_8b98bbd4f3beb4ee0af6843931ad3094ca1a4a67e89bb2d3a0011b7b0698ab66

      # Your store URL, should be updated to where you are hosting your storefront.
      - NEXT_PUBLIC_BASE_URL= http://shop.myhealthybees.com

      # Your preferred default region. When middleware cannot determine the user region from the "x-vercel-country" header, the default region will be used. ISO-2 lowercase format. 
      - NEXT_PUBLIC_DEFAULT_REGION= de

      # Your Stripe public key. See – https://docs.medusajs.com/add-plugins/stripe
      - NEXT_PUBLIC_STRIPE_KEY=

      # Your Next.js revalidation secret. See – https://nextjs.org/docs/app/building-your-application/data-fetching/fetching-caching-and-revalidating#on-demand-revalidation
      - REVALIDATE_SECRET= supersecret

#    build: ./my-h-bees
    # volumes:
    #   - ./my-h-bees-storefront:/app
    ports:
      - "8080:8080"