name: Docker Build Backend
on:
  push:
    branches:
      - master
  workflow_dispatch:
 
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read #This is required for actions/checkout
    steps:
      - uses: actions/checkout@v4
  
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image Admin
        uses: docker/build-push-action@v2
        with:
            context: ./my-h-bees
            push: true
            tags: beejay/my-h-bees:latest
    
      - name: Build and push Docker image Store
        uses: docker/build-push-action@v2
        with:
            context: ./my-h-bees-storefront
            push: true
            tags: beejay/my-h-bees-store:latest

  
