# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - med-shop-back

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read #This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4
  
      - name: Set up Node.js version
        uses: actions/setup-node@v4
        with:
          node-version: '18.x'

      - name: npm install, build, and test
        working-directory: my-h-bees
        run: |
          npm install
          npm run build --if-present

      - name: Copy config
        run: cp ./my-h-bees/medusa-config.js ./my-h-bees/.medusa

      - name: Copy node_modules
        run: cp -r ./my-h-bees/node_modules ./my-h-bees/.medusa

      - name: Zip artifact for deployment
        run: zip release.zip ./my-h-bees/.medusa -r
        

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: release.zip

      - name: Upload medusa admin
        uses: actions/upload-artifact@v4
        with:
           name: admin
           path: |
             ./my-h-bees/.medusa
             ./my-h-bees/node_modules
             ./my-h-bees/medusa-config.js

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write #This is required for requesting the JWT
      contents: read #This is required for actions/checkout

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: admin

      - name: Unzip artifact for deployment
        run: unzip release.zip
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_981BC7E2EDB14A1C8D83AD3EDBBD030D }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_B5D8E30AFBB246DCA7B2E7C00520AE39 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_9490B1775E5C4D77B6208A27432E72FC }}

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'med-shop-back'
          slot-name: 'Production'
          package: .
          
